### ISSUE TITLE
Running the App as a Layman

### ISSUE THREAD

**Issue by sehlceris** [timgabets/electron-atm#10]
Hi, thanks for this neat project. I understand it's no longer maintained, but would still love to play with it. I am a layman to ATM technology and don't know how to set up the first step.

The application requests an "ATM host" to which I am not sure what to provide. Should my local machine be running ATM host software? And am I correct in assuming that this host software is not part of this project? If so, where should I obtain it?

Thanks! And sorry for the noob question.

**Comment by timgabets** [comment]
Hi, thank you for your interest in the application. 

"ATM Host" (ot ATM switch) is a proprietary commercial software which is running on a Linux server or zOS mainframe beside some other payment card processing software. As far as I know, there is no "demo" version of such software, and there's no open-source alternatives as well.

So it seems to me that the easiest way to connect electron-atm app to ATM switch is to get a job in ATM department of a bank, or in a card processing solution vendor (TSYS, Base24, Wirecard etc).

Some time ago I thought about implementing a simple ATM switch, but since I'm not working with ATM acquiring systems anymore, it's very unlikely.
